/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AovDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2036950967631687503L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AovDetail\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"fields\":[{\"name\":\"campaign_id\",\"type\":\"long\"},{\"name\":\"campaign_priority\",\"type\":\"int\"},{\"name\":\"deal_product_id\",\"type\":\"string\"},{\"name\":\"ad_set_id\",\"type\":\"long\"},{\"name\":\"advertiser_type\",\"type\":{\"type\":\"enum\",\"name\":\"AdvertiserType\",\"symbols\":[\"INTERNAL\",\"EXTERNAL\"]}},{\"name\":\"yield_value\",\"type\":\"float\"},{\"name\":\"objective_worth\",\"type\":\"float\"},{\"name\":\"probability_of_objective\",\"type\":\"float\"},{\"name\":\"worth_value\",\"type\":\"float\"},{\"name\":\"worth_funnel_occurrence\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"yield_worth_factor\",\"type\":\"float\"},{\"name\":\"yield_funnel_occurrence\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"yield_prediction_metric\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"aggregated_opportunity_value\",\"type\":\"float\"},{\"name\":\"acceleration_factor\",\"type\":\"float\"},{\"name\":\"pacing_factor\",\"type\":\"float\"},{\"name\":\"budget_spent\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"percentage_budget_spent\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"final_aggregated_opportunity_value\",\"type\":\"float\"},{\"name\":\"metric_used_for_yield_calculation\",\"type\":\"string\"},{\"name\":\"metric_used_for_worth_calculation\",\"type\":\"string\"},{\"name\":\"funnel_used_for_yield_calculation\",\"type\":\"string\"},{\"name\":\"funnel_used_for_worth_calculation\",\"type\":\"string\"},{\"name\":\"data_calculated_at\",\"type\":\"long\"},{\"name\":\"data_considered_upto\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AovDetail> ENCODER =
      new BinaryMessageEncoder<AovDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AovDetail> DECODER =
      new BinaryMessageDecoder<AovDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AovDetail> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AovDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AovDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AovDetail>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AovDetail to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AovDetail from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AovDetail instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AovDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long campaign_id;
  private int campaign_priority;
  private java.lang.CharSequence deal_product_id;
  private long ad_set_id;
  private com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType advertiser_type;
  private float yield_value;
  private float objective_worth;
  private float probability_of_objective;
  private float worth_value;
  private java.lang.Long worth_funnel_occurrence;
  private float yield_worth_factor;
  private java.lang.Long yield_funnel_occurrence;
  private java.lang.Float yield_prediction_metric;
  private float aggregated_opportunity_value;
  private float acceleration_factor;
  private float pacing_factor;
  private java.lang.Float budget_spent;
  private java.lang.Float percentage_budget_spent;
  private float final_aggregated_opportunity_value;
  private java.lang.CharSequence metric_used_for_yield_calculation;
  private java.lang.CharSequence metric_used_for_worth_calculation;
  private java.lang.CharSequence funnel_used_for_yield_calculation;
  private java.lang.CharSequence funnel_used_for_worth_calculation;
  private long data_calculated_at;
  private long data_considered_upto;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AovDetail() {}

  /**
   * All-args constructor.
   * @param campaign_id The new value for campaign_id
   * @param campaign_priority The new value for campaign_priority
   * @param deal_product_id The new value for deal_product_id
   * @param ad_set_id The new value for ad_set_id
   * @param advertiser_type The new value for advertiser_type
   * @param yield_value The new value for yield_value
   * @param objective_worth The new value for objective_worth
   * @param probability_of_objective The new value for probability_of_objective
   * @param worth_value The new value for worth_value
   * @param worth_funnel_occurrence The new value for worth_funnel_occurrence
   * @param yield_worth_factor The new value for yield_worth_factor
   * @param yield_funnel_occurrence The new value for yield_funnel_occurrence
   * @param yield_prediction_metric The new value for yield_prediction_metric
   * @param aggregated_opportunity_value The new value for aggregated_opportunity_value
   * @param acceleration_factor The new value for acceleration_factor
   * @param pacing_factor The new value for pacing_factor
   * @param budget_spent The new value for budget_spent
   * @param percentage_budget_spent The new value for percentage_budget_spent
   * @param final_aggregated_opportunity_value The new value for final_aggregated_opportunity_value
   * @param metric_used_for_yield_calculation The new value for metric_used_for_yield_calculation
   * @param metric_used_for_worth_calculation The new value for metric_used_for_worth_calculation
   * @param funnel_used_for_yield_calculation The new value for funnel_used_for_yield_calculation
   * @param funnel_used_for_worth_calculation The new value for funnel_used_for_worth_calculation
   * @param data_calculated_at The new value for data_calculated_at
   * @param data_considered_upto The new value for data_considered_upto
   */
  public AovDetail(java.lang.Long campaign_id, java.lang.Integer campaign_priority, java.lang.CharSequence deal_product_id, java.lang.Long ad_set_id, com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType advertiser_type, java.lang.Float yield_value, java.lang.Float objective_worth, java.lang.Float probability_of_objective, java.lang.Float worth_value, java.lang.Long worth_funnel_occurrence, java.lang.Float yield_worth_factor, java.lang.Long yield_funnel_occurrence, java.lang.Float yield_prediction_metric, java.lang.Float aggregated_opportunity_value, java.lang.Float acceleration_factor, java.lang.Float pacing_factor, java.lang.Float budget_spent, java.lang.Float percentage_budget_spent, java.lang.Float final_aggregated_opportunity_value, java.lang.CharSequence metric_used_for_yield_calculation, java.lang.CharSequence metric_used_for_worth_calculation, java.lang.CharSequence funnel_used_for_yield_calculation, java.lang.CharSequence funnel_used_for_worth_calculation, java.lang.Long data_calculated_at, java.lang.Long data_considered_upto) {
    this.campaign_id = campaign_id;
    this.campaign_priority = campaign_priority;
    this.deal_product_id = deal_product_id;
    this.ad_set_id = ad_set_id;
    this.advertiser_type = advertiser_type;
    this.yield_value = yield_value;
    this.objective_worth = objective_worth;
    this.probability_of_objective = probability_of_objective;
    this.worth_value = worth_value;
    this.worth_funnel_occurrence = worth_funnel_occurrence;
    this.yield_worth_factor = yield_worth_factor;
    this.yield_funnel_occurrence = yield_funnel_occurrence;
    this.yield_prediction_metric = yield_prediction_metric;
    this.aggregated_opportunity_value = aggregated_opportunity_value;
    this.acceleration_factor = acceleration_factor;
    this.pacing_factor = pacing_factor;
    this.budget_spent = budget_spent;
    this.percentage_budget_spent = percentage_budget_spent;
    this.final_aggregated_opportunity_value = final_aggregated_opportunity_value;
    this.metric_used_for_yield_calculation = metric_used_for_yield_calculation;
    this.metric_used_for_worth_calculation = metric_used_for_worth_calculation;
    this.funnel_used_for_yield_calculation = funnel_used_for_yield_calculation;
    this.funnel_used_for_worth_calculation = funnel_used_for_worth_calculation;
    this.data_calculated_at = data_calculated_at;
    this.data_considered_upto = data_considered_upto;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return campaign_id;
    case 1: return campaign_priority;
    case 2: return deal_product_id;
    case 3: return ad_set_id;
    case 4: return advertiser_type;
    case 5: return yield_value;
    case 6: return objective_worth;
    case 7: return probability_of_objective;
    case 8: return worth_value;
    case 9: return worth_funnel_occurrence;
    case 10: return yield_worth_factor;
    case 11: return yield_funnel_occurrence;
    case 12: return yield_prediction_metric;
    case 13: return aggregated_opportunity_value;
    case 14: return acceleration_factor;
    case 15: return pacing_factor;
    case 16: return budget_spent;
    case 17: return percentage_budget_spent;
    case 18: return final_aggregated_opportunity_value;
    case 19: return metric_used_for_yield_calculation;
    case 20: return metric_used_for_worth_calculation;
    case 21: return funnel_used_for_yield_calculation;
    case 22: return funnel_used_for_worth_calculation;
    case 23: return data_calculated_at;
    case 24: return data_considered_upto;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: campaign_id = (java.lang.Long)value$; break;
    case 1: campaign_priority = (java.lang.Integer)value$; break;
    case 2: deal_product_id = (java.lang.CharSequence)value$; break;
    case 3: ad_set_id = (java.lang.Long)value$; break;
    case 4: advertiser_type = (com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType)value$; break;
    case 5: yield_value = (java.lang.Float)value$; break;
    case 6: objective_worth = (java.lang.Float)value$; break;
    case 7: probability_of_objective = (java.lang.Float)value$; break;
    case 8: worth_value = (java.lang.Float)value$; break;
    case 9: worth_funnel_occurrence = (java.lang.Long)value$; break;
    case 10: yield_worth_factor = (java.lang.Float)value$; break;
    case 11: yield_funnel_occurrence = (java.lang.Long)value$; break;
    case 12: yield_prediction_metric = (java.lang.Float)value$; break;
    case 13: aggregated_opportunity_value = (java.lang.Float)value$; break;
    case 14: acceleration_factor = (java.lang.Float)value$; break;
    case 15: pacing_factor = (java.lang.Float)value$; break;
    case 16: budget_spent = (java.lang.Float)value$; break;
    case 17: percentage_budget_spent = (java.lang.Float)value$; break;
    case 18: final_aggregated_opportunity_value = (java.lang.Float)value$; break;
    case 19: metric_used_for_yield_calculation = (java.lang.CharSequence)value$; break;
    case 20: metric_used_for_worth_calculation = (java.lang.CharSequence)value$; break;
    case 21: funnel_used_for_yield_calculation = (java.lang.CharSequence)value$; break;
    case 22: funnel_used_for_worth_calculation = (java.lang.CharSequence)value$; break;
    case 23: data_calculated_at = (java.lang.Long)value$; break;
    case 24: data_considered_upto = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'campaign_id' field.
   * @return The value of the 'campaign_id' field.
   */
  public long getCampaignId() {
    return campaign_id;
  }


  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(long value) {
    this.campaign_id = value;
  }

  /**
   * Gets the value of the 'campaign_priority' field.
   * @return The value of the 'campaign_priority' field.
   */
  public int getCampaignPriority() {
    return campaign_priority;
  }


  /**
   * Sets the value of the 'campaign_priority' field.
   * @param value the value to set.
   */
  public void setCampaignPriority(int value) {
    this.campaign_priority = value;
  }

  /**
   * Gets the value of the 'deal_product_id' field.
   * @return The value of the 'deal_product_id' field.
   */
  public java.lang.CharSequence getDealProductId() {
    return deal_product_id;
  }


  /**
   * Sets the value of the 'deal_product_id' field.
   * @param value the value to set.
   */
  public void setDealProductId(java.lang.CharSequence value) {
    this.deal_product_id = value;
  }

  /**
   * Gets the value of the 'ad_set_id' field.
   * @return The value of the 'ad_set_id' field.
   */
  public long getAdSetId() {
    return ad_set_id;
  }


  /**
   * Sets the value of the 'ad_set_id' field.
   * @param value the value to set.
   */
  public void setAdSetId(long value) {
    this.ad_set_id = value;
  }

  /**
   * Gets the value of the 'advertiser_type' field.
   * @return The value of the 'advertiser_type' field.
   */
  public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType getAdvertiserType() {
    return advertiser_type;
  }


  /**
   * Sets the value of the 'advertiser_type' field.
   * @param value the value to set.
   */
  public void setAdvertiserType(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType value) {
    this.advertiser_type = value;
  }

  /**
   * Gets the value of the 'yield_value' field.
   * @return The value of the 'yield_value' field.
   */
  public float getYieldValue() {
    return yield_value;
  }


  /**
   * Sets the value of the 'yield_value' field.
   * @param value the value to set.
   */
  public void setYieldValue(float value) {
    this.yield_value = value;
  }

  /**
   * Gets the value of the 'objective_worth' field.
   * @return The value of the 'objective_worth' field.
   */
  public float getObjectiveWorth() {
    return objective_worth;
  }


  /**
   * Sets the value of the 'objective_worth' field.
   * @param value the value to set.
   */
  public void setObjectiveWorth(float value) {
    this.objective_worth = value;
  }

  /**
   * Gets the value of the 'probability_of_objective' field.
   * @return The value of the 'probability_of_objective' field.
   */
  public float getProbabilityOfObjective() {
    return probability_of_objective;
  }


  /**
   * Sets the value of the 'probability_of_objective' field.
   * @param value the value to set.
   */
  public void setProbabilityOfObjective(float value) {
    this.probability_of_objective = value;
  }

  /**
   * Gets the value of the 'worth_value' field.
   * @return The value of the 'worth_value' field.
   */
  public float getWorthValue() {
    return worth_value;
  }


  /**
   * Sets the value of the 'worth_value' field.
   * @param value the value to set.
   */
  public void setWorthValue(float value) {
    this.worth_value = value;
  }

  /**
   * Gets the value of the 'worth_funnel_occurrence' field.
   * @return The value of the 'worth_funnel_occurrence' field.
   */
  public java.lang.Long getWorthFunnelOccurrence() {
    return worth_funnel_occurrence;
  }


  /**
   * Sets the value of the 'worth_funnel_occurrence' field.
   * @param value the value to set.
   */
  public void setWorthFunnelOccurrence(java.lang.Long value) {
    this.worth_funnel_occurrence = value;
  }

  /**
   * Gets the value of the 'yield_worth_factor' field.
   * @return The value of the 'yield_worth_factor' field.
   */
  public float getYieldWorthFactor() {
    return yield_worth_factor;
  }


  /**
   * Sets the value of the 'yield_worth_factor' field.
   * @param value the value to set.
   */
  public void setYieldWorthFactor(float value) {
    this.yield_worth_factor = value;
  }

  /**
   * Gets the value of the 'yield_funnel_occurrence' field.
   * @return The value of the 'yield_funnel_occurrence' field.
   */
  public java.lang.Long getYieldFunnelOccurrence() {
    return yield_funnel_occurrence;
  }


  /**
   * Sets the value of the 'yield_funnel_occurrence' field.
   * @param value the value to set.
   */
  public void setYieldFunnelOccurrence(java.lang.Long value) {
    this.yield_funnel_occurrence = value;
  }

  /**
   * Gets the value of the 'yield_prediction_metric' field.
   * @return The value of the 'yield_prediction_metric' field.
   */
  public java.lang.Float getYieldPredictionMetric() {
    return yield_prediction_metric;
  }


  /**
   * Sets the value of the 'yield_prediction_metric' field.
   * @param value the value to set.
   */
  public void setYieldPredictionMetric(java.lang.Float value) {
    this.yield_prediction_metric = value;
  }

  /**
   * Gets the value of the 'aggregated_opportunity_value' field.
   * @return The value of the 'aggregated_opportunity_value' field.
   */
  public float getAggregatedOpportunityValue() {
    return aggregated_opportunity_value;
  }


  /**
   * Sets the value of the 'aggregated_opportunity_value' field.
   * @param value the value to set.
   */
  public void setAggregatedOpportunityValue(float value) {
    this.aggregated_opportunity_value = value;
  }

  /**
   * Gets the value of the 'acceleration_factor' field.
   * @return The value of the 'acceleration_factor' field.
   */
  public float getAccelerationFactor() {
    return acceleration_factor;
  }


  /**
   * Sets the value of the 'acceleration_factor' field.
   * @param value the value to set.
   */
  public void setAccelerationFactor(float value) {
    this.acceleration_factor = value;
  }

  /**
   * Gets the value of the 'pacing_factor' field.
   * @return The value of the 'pacing_factor' field.
   */
  public float getPacingFactor() {
    return pacing_factor;
  }


  /**
   * Sets the value of the 'pacing_factor' field.
   * @param value the value to set.
   */
  public void setPacingFactor(float value) {
    this.pacing_factor = value;
  }

  /**
   * Gets the value of the 'budget_spent' field.
   * @return The value of the 'budget_spent' field.
   */
  public java.lang.Float getBudgetSpent() {
    return budget_spent;
  }


  /**
   * Sets the value of the 'budget_spent' field.
   * @param value the value to set.
   */
  public void setBudgetSpent(java.lang.Float value) {
    this.budget_spent = value;
  }

  /**
   * Gets the value of the 'percentage_budget_spent' field.
   * @return The value of the 'percentage_budget_spent' field.
   */
  public java.lang.Float getPercentageBudgetSpent() {
    return percentage_budget_spent;
  }


  /**
   * Sets the value of the 'percentage_budget_spent' field.
   * @param value the value to set.
   */
  public void setPercentageBudgetSpent(java.lang.Float value) {
    this.percentage_budget_spent = value;
  }

  /**
   * Gets the value of the 'final_aggregated_opportunity_value' field.
   * @return The value of the 'final_aggregated_opportunity_value' field.
   */
  public float getFinalAggregatedOpportunityValue() {
    return final_aggregated_opportunity_value;
  }


  /**
   * Sets the value of the 'final_aggregated_opportunity_value' field.
   * @param value the value to set.
   */
  public void setFinalAggregatedOpportunityValue(float value) {
    this.final_aggregated_opportunity_value = value;
  }

  /**
   * Gets the value of the 'metric_used_for_yield_calculation' field.
   * @return The value of the 'metric_used_for_yield_calculation' field.
   */
  public java.lang.CharSequence getMetricUsedForYieldCalculation() {
    return metric_used_for_yield_calculation;
  }


  /**
   * Sets the value of the 'metric_used_for_yield_calculation' field.
   * @param value the value to set.
   */
  public void setMetricUsedForYieldCalculation(java.lang.CharSequence value) {
    this.metric_used_for_yield_calculation = value;
  }

  /**
   * Gets the value of the 'metric_used_for_worth_calculation' field.
   * @return The value of the 'metric_used_for_worth_calculation' field.
   */
  public java.lang.CharSequence getMetricUsedForWorthCalculation() {
    return metric_used_for_worth_calculation;
  }


  /**
   * Sets the value of the 'metric_used_for_worth_calculation' field.
   * @param value the value to set.
   */
  public void setMetricUsedForWorthCalculation(java.lang.CharSequence value) {
    this.metric_used_for_worth_calculation = value;
  }

  /**
   * Gets the value of the 'funnel_used_for_yield_calculation' field.
   * @return The value of the 'funnel_used_for_yield_calculation' field.
   */
  public java.lang.CharSequence getFunnelUsedForYieldCalculation() {
    return funnel_used_for_yield_calculation;
  }


  /**
   * Sets the value of the 'funnel_used_for_yield_calculation' field.
   * @param value the value to set.
   */
  public void setFunnelUsedForYieldCalculation(java.lang.CharSequence value) {
    this.funnel_used_for_yield_calculation = value;
  }

  /**
   * Gets the value of the 'funnel_used_for_worth_calculation' field.
   * @return The value of the 'funnel_used_for_worth_calculation' field.
   */
  public java.lang.CharSequence getFunnelUsedForWorthCalculation() {
    return funnel_used_for_worth_calculation;
  }


  /**
   * Sets the value of the 'funnel_used_for_worth_calculation' field.
   * @param value the value to set.
   */
  public void setFunnelUsedForWorthCalculation(java.lang.CharSequence value) {
    this.funnel_used_for_worth_calculation = value;
  }

  /**
   * Gets the value of the 'data_calculated_at' field.
   * @return The value of the 'data_calculated_at' field.
   */
  public long getDataCalculatedAt() {
    return data_calculated_at;
  }


  /**
   * Sets the value of the 'data_calculated_at' field.
   * @param value the value to set.
   */
  public void setDataCalculatedAt(long value) {
    this.data_calculated_at = value;
  }

  /**
   * Gets the value of the 'data_considered_upto' field.
   * @return The value of the 'data_considered_upto' field.
   */
  public long getDataConsideredUpto() {
    return data_considered_upto;
  }


  /**
   * Sets the value of the 'data_considered_upto' field.
   * @param value the value to set.
   */
  public void setDataConsideredUpto(long value) {
    this.data_considered_upto = value;
  }

  /**
   * Creates a new AovDetail RecordBuilder.
   * @return A new AovDetail RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder newBuilder() {
    return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder();
  }

  /**
   * Creates a new AovDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AovDetail RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder newBuilder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder other) {
    if (other == null) {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder();
    } else {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder(other);
    }
  }

  /**
   * Creates a new AovDetail RecordBuilder by copying an existing AovDetail instance.
   * @param other The existing instance to copy.
   * @return A new AovDetail RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder newBuilder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail other) {
    if (other == null) {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder();
    } else {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder(other);
    }
  }

  /**
   * RecordBuilder for AovDetail instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AovDetail>
    implements org.apache.avro.data.RecordBuilder<AovDetail> {

    private long campaign_id;
    private int campaign_priority;
    private java.lang.CharSequence deal_product_id;
    private long ad_set_id;
    private com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType advertiser_type;
    private float yield_value;
    private float objective_worth;
    private float probability_of_objective;
    private float worth_value;
    private java.lang.Long worth_funnel_occurrence;
    private float yield_worth_factor;
    private java.lang.Long yield_funnel_occurrence;
    private java.lang.Float yield_prediction_metric;
    private float aggregated_opportunity_value;
    private float acceleration_factor;
    private float pacing_factor;
    private java.lang.Float budget_spent;
    private java.lang.Float percentage_budget_spent;
    private float final_aggregated_opportunity_value;
    private java.lang.CharSequence metric_used_for_yield_calculation;
    private java.lang.CharSequence metric_used_for_worth_calculation;
    private java.lang.CharSequence funnel_used_for_yield_calculation;
    private java.lang.CharSequence funnel_used_for_worth_calculation;
    private long data_calculated_at;
    private long data_considered_upto;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[0].schema(), other.campaign_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.campaign_priority)) {
        this.campaign_priority = data().deepCopy(fields()[1].schema(), other.campaign_priority);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.deal_product_id)) {
        this.deal_product_id = data().deepCopy(fields()[2].schema(), other.deal_product_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ad_set_id)) {
        this.ad_set_id = data().deepCopy(fields()[3].schema(), other.ad_set_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.advertiser_type)) {
        this.advertiser_type = data().deepCopy(fields()[4].schema(), other.advertiser_type);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.yield_value)) {
        this.yield_value = data().deepCopy(fields()[5].schema(), other.yield_value);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.objective_worth)) {
        this.objective_worth = data().deepCopy(fields()[6].schema(), other.objective_worth);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.probability_of_objective)) {
        this.probability_of_objective = data().deepCopy(fields()[7].schema(), other.probability_of_objective);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.worth_value)) {
        this.worth_value = data().deepCopy(fields()[8].schema(), other.worth_value);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.worth_funnel_occurrence)) {
        this.worth_funnel_occurrence = data().deepCopy(fields()[9].schema(), other.worth_funnel_occurrence);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.yield_worth_factor)) {
        this.yield_worth_factor = data().deepCopy(fields()[10].schema(), other.yield_worth_factor);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.yield_funnel_occurrence)) {
        this.yield_funnel_occurrence = data().deepCopy(fields()[11].schema(), other.yield_funnel_occurrence);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.yield_prediction_metric)) {
        this.yield_prediction_metric = data().deepCopy(fields()[12].schema(), other.yield_prediction_metric);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.aggregated_opportunity_value)) {
        this.aggregated_opportunity_value = data().deepCopy(fields()[13].schema(), other.aggregated_opportunity_value);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.acceleration_factor)) {
        this.acceleration_factor = data().deepCopy(fields()[14].schema(), other.acceleration_factor);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.pacing_factor)) {
        this.pacing_factor = data().deepCopy(fields()[15].schema(), other.pacing_factor);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.budget_spent)) {
        this.budget_spent = data().deepCopy(fields()[16].schema(), other.budget_spent);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.percentage_budget_spent)) {
        this.percentage_budget_spent = data().deepCopy(fields()[17].schema(), other.percentage_budget_spent);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.final_aggregated_opportunity_value)) {
        this.final_aggregated_opportunity_value = data().deepCopy(fields()[18].schema(), other.final_aggregated_opportunity_value);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.metric_used_for_yield_calculation)) {
        this.metric_used_for_yield_calculation = data().deepCopy(fields()[19].schema(), other.metric_used_for_yield_calculation);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.metric_used_for_worth_calculation)) {
        this.metric_used_for_worth_calculation = data().deepCopy(fields()[20].schema(), other.metric_used_for_worth_calculation);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.funnel_used_for_yield_calculation)) {
        this.funnel_used_for_yield_calculation = data().deepCopy(fields()[21].schema(), other.funnel_used_for_yield_calculation);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.funnel_used_for_worth_calculation)) {
        this.funnel_used_for_worth_calculation = data().deepCopy(fields()[22].schema(), other.funnel_used_for_worth_calculation);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.data_calculated_at)) {
        this.data_calculated_at = data().deepCopy(fields()[23].schema(), other.data_calculated_at);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.data_considered_upto)) {
        this.data_considered_upto = data().deepCopy(fields()[24].schema(), other.data_considered_upto);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
    }

    /**
     * Creates a Builder by copying an existing AovDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[0].schema(), other.campaign_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.campaign_priority)) {
        this.campaign_priority = data().deepCopy(fields()[1].schema(), other.campaign_priority);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deal_product_id)) {
        this.deal_product_id = data().deepCopy(fields()[2].schema(), other.deal_product_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ad_set_id)) {
        this.ad_set_id = data().deepCopy(fields()[3].schema(), other.ad_set_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.advertiser_type)) {
        this.advertiser_type = data().deepCopy(fields()[4].schema(), other.advertiser_type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.yield_value)) {
        this.yield_value = data().deepCopy(fields()[5].schema(), other.yield_value);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.objective_worth)) {
        this.objective_worth = data().deepCopy(fields()[6].schema(), other.objective_worth);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.probability_of_objective)) {
        this.probability_of_objective = data().deepCopy(fields()[7].schema(), other.probability_of_objective);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.worth_value)) {
        this.worth_value = data().deepCopy(fields()[8].schema(), other.worth_value);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.worth_funnel_occurrence)) {
        this.worth_funnel_occurrence = data().deepCopy(fields()[9].schema(), other.worth_funnel_occurrence);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.yield_worth_factor)) {
        this.yield_worth_factor = data().deepCopy(fields()[10].schema(), other.yield_worth_factor);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.yield_funnel_occurrence)) {
        this.yield_funnel_occurrence = data().deepCopy(fields()[11].schema(), other.yield_funnel_occurrence);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.yield_prediction_metric)) {
        this.yield_prediction_metric = data().deepCopy(fields()[12].schema(), other.yield_prediction_metric);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.aggregated_opportunity_value)) {
        this.aggregated_opportunity_value = data().deepCopy(fields()[13].schema(), other.aggregated_opportunity_value);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.acceleration_factor)) {
        this.acceleration_factor = data().deepCopy(fields()[14].schema(), other.acceleration_factor);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.pacing_factor)) {
        this.pacing_factor = data().deepCopy(fields()[15].schema(), other.pacing_factor);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.budget_spent)) {
        this.budget_spent = data().deepCopy(fields()[16].schema(), other.budget_spent);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.percentage_budget_spent)) {
        this.percentage_budget_spent = data().deepCopy(fields()[17].schema(), other.percentage_budget_spent);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.final_aggregated_opportunity_value)) {
        this.final_aggregated_opportunity_value = data().deepCopy(fields()[18].schema(), other.final_aggregated_opportunity_value);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.metric_used_for_yield_calculation)) {
        this.metric_used_for_yield_calculation = data().deepCopy(fields()[19].schema(), other.metric_used_for_yield_calculation);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.metric_used_for_worth_calculation)) {
        this.metric_used_for_worth_calculation = data().deepCopy(fields()[20].schema(), other.metric_used_for_worth_calculation);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.funnel_used_for_yield_calculation)) {
        this.funnel_used_for_yield_calculation = data().deepCopy(fields()[21].schema(), other.funnel_used_for_yield_calculation);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.funnel_used_for_worth_calculation)) {
        this.funnel_used_for_worth_calculation = data().deepCopy(fields()[22].schema(), other.funnel_used_for_worth_calculation);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.data_calculated_at)) {
        this.data_calculated_at = data().deepCopy(fields()[23].schema(), other.data_calculated_at);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.data_considered_upto)) {
        this.data_considered_upto = data().deepCopy(fields()[24].schema(), other.data_considered_upto);
        fieldSetFlags()[24] = true;
      }
    }

    /**
      * Gets the value of the 'campaign_id' field.
      * @return The value.
      */
    public long getCampaignId() {
      return campaign_id;
    }


    /**
      * Sets the value of the 'campaign_id' field.
      * @param value The value of 'campaign_id'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setCampaignId(long value) {
      validate(fields()[0], value);
      this.campaign_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_id' field has been set.
      * @return True if the 'campaign_id' field has been set, false otherwise.
      */
    public boolean hasCampaignId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'campaign_id' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearCampaignId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaign_priority' field.
      * @return The value.
      */
    public int getCampaignPriority() {
      return campaign_priority;
    }


    /**
      * Sets the value of the 'campaign_priority' field.
      * @param value The value of 'campaign_priority'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setCampaignPriority(int value) {
      validate(fields()[1], value);
      this.campaign_priority = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_priority' field has been set.
      * @return True if the 'campaign_priority' field has been set, false otherwise.
      */
    public boolean hasCampaignPriority() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'campaign_priority' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearCampaignPriority() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'deal_product_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getDealProductId() {
      return deal_product_id;
    }


    /**
      * Sets the value of the 'deal_product_id' field.
      * @param value The value of 'deal_product_id'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setDealProductId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.deal_product_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'deal_product_id' field has been set.
      * @return True if the 'deal_product_id' field has been set, false otherwise.
      */
    public boolean hasDealProductId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'deal_product_id' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearDealProductId() {
      deal_product_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ad_set_id' field.
      * @return The value.
      */
    public long getAdSetId() {
      return ad_set_id;
    }


    /**
      * Sets the value of the 'ad_set_id' field.
      * @param value The value of 'ad_set_id'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setAdSetId(long value) {
      validate(fields()[3], value);
      this.ad_set_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ad_set_id' field has been set.
      * @return True if the 'ad_set_id' field has been set, false otherwise.
      */
    public boolean hasAdSetId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ad_set_id' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearAdSetId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'advertiser_type' field.
      * @return The value.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType getAdvertiserType() {
      return advertiser_type;
    }


    /**
      * Sets the value of the 'advertiser_type' field.
      * @param value The value of 'advertiser_type'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setAdvertiserType(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType value) {
      validate(fields()[4], value);
      this.advertiser_type = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'advertiser_type' field has been set.
      * @return True if the 'advertiser_type' field has been set, false otherwise.
      */
    public boolean hasAdvertiserType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'advertiser_type' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearAdvertiserType() {
      advertiser_type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'yield_value' field.
      * @return The value.
      */
    public float getYieldValue() {
      return yield_value;
    }


    /**
      * Sets the value of the 'yield_value' field.
      * @param value The value of 'yield_value'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setYieldValue(float value) {
      validate(fields()[5], value);
      this.yield_value = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'yield_value' field has been set.
      * @return True if the 'yield_value' field has been set, false otherwise.
      */
    public boolean hasYieldValue() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'yield_value' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearYieldValue() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'objective_worth' field.
      * @return The value.
      */
    public float getObjectiveWorth() {
      return objective_worth;
    }


    /**
      * Sets the value of the 'objective_worth' field.
      * @param value The value of 'objective_worth'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setObjectiveWorth(float value) {
      validate(fields()[6], value);
      this.objective_worth = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'objective_worth' field has been set.
      * @return True if the 'objective_worth' field has been set, false otherwise.
      */
    public boolean hasObjectiveWorth() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'objective_worth' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearObjectiveWorth() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'probability_of_objective' field.
      * @return The value.
      */
    public float getProbabilityOfObjective() {
      return probability_of_objective;
    }


    /**
      * Sets the value of the 'probability_of_objective' field.
      * @param value The value of 'probability_of_objective'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setProbabilityOfObjective(float value) {
      validate(fields()[7], value);
      this.probability_of_objective = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'probability_of_objective' field has been set.
      * @return True if the 'probability_of_objective' field has been set, false otherwise.
      */
    public boolean hasProbabilityOfObjective() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'probability_of_objective' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearProbabilityOfObjective() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'worth_value' field.
      * @return The value.
      */
    public float getWorthValue() {
      return worth_value;
    }


    /**
      * Sets the value of the 'worth_value' field.
      * @param value The value of 'worth_value'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setWorthValue(float value) {
      validate(fields()[8], value);
      this.worth_value = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'worth_value' field has been set.
      * @return True if the 'worth_value' field has been set, false otherwise.
      */
    public boolean hasWorthValue() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'worth_value' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearWorthValue() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'worth_funnel_occurrence' field.
      * @return The value.
      */
    public java.lang.Long getWorthFunnelOccurrence() {
      return worth_funnel_occurrence;
    }


    /**
      * Sets the value of the 'worth_funnel_occurrence' field.
      * @param value The value of 'worth_funnel_occurrence'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setWorthFunnelOccurrence(java.lang.Long value) {
      validate(fields()[9], value);
      this.worth_funnel_occurrence = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'worth_funnel_occurrence' field has been set.
      * @return True if the 'worth_funnel_occurrence' field has been set, false otherwise.
      */
    public boolean hasWorthFunnelOccurrence() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'worth_funnel_occurrence' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearWorthFunnelOccurrence() {
      worth_funnel_occurrence = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'yield_worth_factor' field.
      * @return The value.
      */
    public float getYieldWorthFactor() {
      return yield_worth_factor;
    }


    /**
      * Sets the value of the 'yield_worth_factor' field.
      * @param value The value of 'yield_worth_factor'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setYieldWorthFactor(float value) {
      validate(fields()[10], value);
      this.yield_worth_factor = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'yield_worth_factor' field has been set.
      * @return True if the 'yield_worth_factor' field has been set, false otherwise.
      */
    public boolean hasYieldWorthFactor() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'yield_worth_factor' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearYieldWorthFactor() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'yield_funnel_occurrence' field.
      * @return The value.
      */
    public java.lang.Long getYieldFunnelOccurrence() {
      return yield_funnel_occurrence;
    }


    /**
      * Sets the value of the 'yield_funnel_occurrence' field.
      * @param value The value of 'yield_funnel_occurrence'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setYieldFunnelOccurrence(java.lang.Long value) {
      validate(fields()[11], value);
      this.yield_funnel_occurrence = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'yield_funnel_occurrence' field has been set.
      * @return True if the 'yield_funnel_occurrence' field has been set, false otherwise.
      */
    public boolean hasYieldFunnelOccurrence() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'yield_funnel_occurrence' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearYieldFunnelOccurrence() {
      yield_funnel_occurrence = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'yield_prediction_metric' field.
      * @return The value.
      */
    public java.lang.Float getYieldPredictionMetric() {
      return yield_prediction_metric;
    }


    /**
      * Sets the value of the 'yield_prediction_metric' field.
      * @param value The value of 'yield_prediction_metric'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setYieldPredictionMetric(java.lang.Float value) {
      validate(fields()[12], value);
      this.yield_prediction_metric = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'yield_prediction_metric' field has been set.
      * @return True if the 'yield_prediction_metric' field has been set, false otherwise.
      */
    public boolean hasYieldPredictionMetric() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'yield_prediction_metric' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearYieldPredictionMetric() {
      yield_prediction_metric = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregated_opportunity_value' field.
      * @return The value.
      */
    public float getAggregatedOpportunityValue() {
      return aggregated_opportunity_value;
    }


    /**
      * Sets the value of the 'aggregated_opportunity_value' field.
      * @param value The value of 'aggregated_opportunity_value'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setAggregatedOpportunityValue(float value) {
      validate(fields()[13], value);
      this.aggregated_opportunity_value = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregated_opportunity_value' field has been set.
      * @return True if the 'aggregated_opportunity_value' field has been set, false otherwise.
      */
    public boolean hasAggregatedOpportunityValue() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'aggregated_opportunity_value' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearAggregatedOpportunityValue() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'acceleration_factor' field.
      * @return The value.
      */
    public float getAccelerationFactor() {
      return acceleration_factor;
    }


    /**
      * Sets the value of the 'acceleration_factor' field.
      * @param value The value of 'acceleration_factor'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setAccelerationFactor(float value) {
      validate(fields()[14], value);
      this.acceleration_factor = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'acceleration_factor' field has been set.
      * @return True if the 'acceleration_factor' field has been set, false otherwise.
      */
    public boolean hasAccelerationFactor() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'acceleration_factor' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearAccelerationFactor() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'pacing_factor' field.
      * @return The value.
      */
    public float getPacingFactor() {
      return pacing_factor;
    }


    /**
      * Sets the value of the 'pacing_factor' field.
      * @param value The value of 'pacing_factor'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setPacingFactor(float value) {
      validate(fields()[15], value);
      this.pacing_factor = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'pacing_factor' field has been set.
      * @return True if the 'pacing_factor' field has been set, false otherwise.
      */
    public boolean hasPacingFactor() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'pacing_factor' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearPacingFactor() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'budget_spent' field.
      * @return The value.
      */
    public java.lang.Float getBudgetSpent() {
      return budget_spent;
    }


    /**
      * Sets the value of the 'budget_spent' field.
      * @param value The value of 'budget_spent'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setBudgetSpent(java.lang.Float value) {
      validate(fields()[16], value);
      this.budget_spent = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'budget_spent' field has been set.
      * @return True if the 'budget_spent' field has been set, false otherwise.
      */
    public boolean hasBudgetSpent() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'budget_spent' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearBudgetSpent() {
      budget_spent = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'percentage_budget_spent' field.
      * @return The value.
      */
    public java.lang.Float getPercentageBudgetSpent() {
      return percentage_budget_spent;
    }


    /**
      * Sets the value of the 'percentage_budget_spent' field.
      * @param value The value of 'percentage_budget_spent'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setPercentageBudgetSpent(java.lang.Float value) {
      validate(fields()[17], value);
      this.percentage_budget_spent = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'percentage_budget_spent' field has been set.
      * @return True if the 'percentage_budget_spent' field has been set, false otherwise.
      */
    public boolean hasPercentageBudgetSpent() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'percentage_budget_spent' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearPercentageBudgetSpent() {
      percentage_budget_spent = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'final_aggregated_opportunity_value' field.
      * @return The value.
      */
    public float getFinalAggregatedOpportunityValue() {
      return final_aggregated_opportunity_value;
    }


    /**
      * Sets the value of the 'final_aggregated_opportunity_value' field.
      * @param value The value of 'final_aggregated_opportunity_value'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setFinalAggregatedOpportunityValue(float value) {
      validate(fields()[18], value);
      this.final_aggregated_opportunity_value = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'final_aggregated_opportunity_value' field has been set.
      * @return True if the 'final_aggregated_opportunity_value' field has been set, false otherwise.
      */
    public boolean hasFinalAggregatedOpportunityValue() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'final_aggregated_opportunity_value' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearFinalAggregatedOpportunityValue() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'metric_used_for_yield_calculation' field.
      * @return The value.
      */
    public java.lang.CharSequence getMetricUsedForYieldCalculation() {
      return metric_used_for_yield_calculation;
    }


    /**
      * Sets the value of the 'metric_used_for_yield_calculation' field.
      * @param value The value of 'metric_used_for_yield_calculation'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setMetricUsedForYieldCalculation(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.metric_used_for_yield_calculation = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'metric_used_for_yield_calculation' field has been set.
      * @return True if the 'metric_used_for_yield_calculation' field has been set, false otherwise.
      */
    public boolean hasMetricUsedForYieldCalculation() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'metric_used_for_yield_calculation' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearMetricUsedForYieldCalculation() {
      metric_used_for_yield_calculation = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'metric_used_for_worth_calculation' field.
      * @return The value.
      */
    public java.lang.CharSequence getMetricUsedForWorthCalculation() {
      return metric_used_for_worth_calculation;
    }


    /**
      * Sets the value of the 'metric_used_for_worth_calculation' field.
      * @param value The value of 'metric_used_for_worth_calculation'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setMetricUsedForWorthCalculation(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.metric_used_for_worth_calculation = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'metric_used_for_worth_calculation' field has been set.
      * @return True if the 'metric_used_for_worth_calculation' field has been set, false otherwise.
      */
    public boolean hasMetricUsedForWorthCalculation() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'metric_used_for_worth_calculation' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearMetricUsedForWorthCalculation() {
      metric_used_for_worth_calculation = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'funnel_used_for_yield_calculation' field.
      * @return The value.
      */
    public java.lang.CharSequence getFunnelUsedForYieldCalculation() {
      return funnel_used_for_yield_calculation;
    }


    /**
      * Sets the value of the 'funnel_used_for_yield_calculation' field.
      * @param value The value of 'funnel_used_for_yield_calculation'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setFunnelUsedForYieldCalculation(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.funnel_used_for_yield_calculation = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'funnel_used_for_yield_calculation' field has been set.
      * @return True if the 'funnel_used_for_yield_calculation' field has been set, false otherwise.
      */
    public boolean hasFunnelUsedForYieldCalculation() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'funnel_used_for_yield_calculation' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearFunnelUsedForYieldCalculation() {
      funnel_used_for_yield_calculation = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'funnel_used_for_worth_calculation' field.
      * @return The value.
      */
    public java.lang.CharSequence getFunnelUsedForWorthCalculation() {
      return funnel_used_for_worth_calculation;
    }


    /**
      * Sets the value of the 'funnel_used_for_worth_calculation' field.
      * @param value The value of 'funnel_used_for_worth_calculation'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setFunnelUsedForWorthCalculation(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.funnel_used_for_worth_calculation = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'funnel_used_for_worth_calculation' field has been set.
      * @return True if the 'funnel_used_for_worth_calculation' field has been set, false otherwise.
      */
    public boolean hasFunnelUsedForWorthCalculation() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'funnel_used_for_worth_calculation' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearFunnelUsedForWorthCalculation() {
      funnel_used_for_worth_calculation = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'data_calculated_at' field.
      * @return The value.
      */
    public long getDataCalculatedAt() {
      return data_calculated_at;
    }


    /**
      * Sets the value of the 'data_calculated_at' field.
      * @param value The value of 'data_calculated_at'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setDataCalculatedAt(long value) {
      validate(fields()[23], value);
      this.data_calculated_at = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'data_calculated_at' field has been set.
      * @return True if the 'data_calculated_at' field has been set, false otherwise.
      */
    public boolean hasDataCalculatedAt() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'data_calculated_at' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearDataCalculatedAt() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'data_considered_upto' field.
      * @return The value.
      */
    public long getDataConsideredUpto() {
      return data_considered_upto;
    }


    /**
      * Sets the value of the 'data_considered_upto' field.
      * @param value The value of 'data_considered_upto'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder setDataConsideredUpto(long value) {
      validate(fields()[24], value);
      this.data_considered_upto = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'data_considered_upto' field has been set.
      * @return True if the 'data_considered_upto' field has been set, false otherwise.
      */
    public boolean hasDataConsideredUpto() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'data_considered_upto' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AovDetail.Builder clearDataConsideredUpto() {
      fieldSetFlags()[24] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AovDetail build() {
      try {
        AovDetail record = new AovDetail();
        record.campaign_id = fieldSetFlags()[0] ? this.campaign_id : (java.lang.Long) defaultValue(fields()[0]);
        record.campaign_priority = fieldSetFlags()[1] ? this.campaign_priority : (java.lang.Integer) defaultValue(fields()[1]);
        record.deal_product_id = fieldSetFlags()[2] ? this.deal_product_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ad_set_id = fieldSetFlags()[3] ? this.ad_set_id : (java.lang.Long) defaultValue(fields()[3]);
        record.advertiser_type = fieldSetFlags()[4] ? this.advertiser_type : (com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType) defaultValue(fields()[4]);
        record.yield_value = fieldSetFlags()[5] ? this.yield_value : (java.lang.Float) defaultValue(fields()[5]);
        record.objective_worth = fieldSetFlags()[6] ? this.objective_worth : (java.lang.Float) defaultValue(fields()[6]);
        record.probability_of_objective = fieldSetFlags()[7] ? this.probability_of_objective : (java.lang.Float) defaultValue(fields()[7]);
        record.worth_value = fieldSetFlags()[8] ? this.worth_value : (java.lang.Float) defaultValue(fields()[8]);
        record.worth_funnel_occurrence = fieldSetFlags()[9] ? this.worth_funnel_occurrence : (java.lang.Long) defaultValue(fields()[9]);
        record.yield_worth_factor = fieldSetFlags()[10] ? this.yield_worth_factor : (java.lang.Float) defaultValue(fields()[10]);
        record.yield_funnel_occurrence = fieldSetFlags()[11] ? this.yield_funnel_occurrence : (java.lang.Long) defaultValue(fields()[11]);
        record.yield_prediction_metric = fieldSetFlags()[12] ? this.yield_prediction_metric : (java.lang.Float) defaultValue(fields()[12]);
        record.aggregated_opportunity_value = fieldSetFlags()[13] ? this.aggregated_opportunity_value : (java.lang.Float) defaultValue(fields()[13]);
        record.acceleration_factor = fieldSetFlags()[14] ? this.acceleration_factor : (java.lang.Float) defaultValue(fields()[14]);
        record.pacing_factor = fieldSetFlags()[15] ? this.pacing_factor : (java.lang.Float) defaultValue(fields()[15]);
        record.budget_spent = fieldSetFlags()[16] ? this.budget_spent : (java.lang.Float) defaultValue(fields()[16]);
        record.percentage_budget_spent = fieldSetFlags()[17] ? this.percentage_budget_spent : (java.lang.Float) defaultValue(fields()[17]);
        record.final_aggregated_opportunity_value = fieldSetFlags()[18] ? this.final_aggregated_opportunity_value : (java.lang.Float) defaultValue(fields()[18]);
        record.metric_used_for_yield_calculation = fieldSetFlags()[19] ? this.metric_used_for_yield_calculation : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.metric_used_for_worth_calculation = fieldSetFlags()[20] ? this.metric_used_for_worth_calculation : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.funnel_used_for_yield_calculation = fieldSetFlags()[21] ? this.funnel_used_for_yield_calculation : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.funnel_used_for_worth_calculation = fieldSetFlags()[22] ? this.funnel_used_for_worth_calculation : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.data_calculated_at = fieldSetFlags()[23] ? this.data_calculated_at : (java.lang.Long) defaultValue(fields()[23]);
        record.data_considered_upto = fieldSetFlags()[24] ? this.data_considered_upto : (java.lang.Long) defaultValue(fields()[24]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AovDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<AovDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AovDetail>
    READER$ = (org.apache.avro.io.DatumReader<AovDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.campaign_id);

    out.writeInt(this.campaign_priority);

    out.writeString(this.deal_product_id);

    out.writeLong(this.ad_set_id);

    out.writeEnum(this.advertiser_type.ordinal());

    out.writeFloat(this.yield_value);

    out.writeFloat(this.objective_worth);

    out.writeFloat(this.probability_of_objective);

    out.writeFloat(this.worth_value);

    if (this.worth_funnel_occurrence == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.worth_funnel_occurrence);
    }

    out.writeFloat(this.yield_worth_factor);

    if (this.yield_funnel_occurrence == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.yield_funnel_occurrence);
    }

    if (this.yield_prediction_metric == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.yield_prediction_metric);
    }

    out.writeFloat(this.aggregated_opportunity_value);

    out.writeFloat(this.acceleration_factor);

    out.writeFloat(this.pacing_factor);

    if (this.budget_spent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.budget_spent);
    }

    if (this.percentage_budget_spent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.percentage_budget_spent);
    }

    out.writeFloat(this.final_aggregated_opportunity_value);

    out.writeString(this.metric_used_for_yield_calculation);

    out.writeString(this.metric_used_for_worth_calculation);

    out.writeString(this.funnel_used_for_yield_calculation);

    out.writeString(this.funnel_used_for_worth_calculation);

    out.writeLong(this.data_calculated_at);

    out.writeLong(this.data_considered_upto);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.campaign_id = in.readLong();

      this.campaign_priority = in.readInt();

      this.deal_product_id = in.readString(this.deal_product_id instanceof Utf8 ? (Utf8)this.deal_product_id : null);

      this.ad_set_id = in.readLong();

      this.advertiser_type = com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType.values()[in.readEnum()];

      this.yield_value = in.readFloat();

      this.objective_worth = in.readFloat();

      this.probability_of_objective = in.readFloat();

      this.worth_value = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.worth_funnel_occurrence = null;
      } else {
        this.worth_funnel_occurrence = in.readLong();
      }

      this.yield_worth_factor = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.yield_funnel_occurrence = null;
      } else {
        this.yield_funnel_occurrence = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.yield_prediction_metric = null;
      } else {
        this.yield_prediction_metric = in.readFloat();
      }

      this.aggregated_opportunity_value = in.readFloat();

      this.acceleration_factor = in.readFloat();

      this.pacing_factor = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.budget_spent = null;
      } else {
        this.budget_spent = in.readFloat();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.percentage_budget_spent = null;
      } else {
        this.percentage_budget_spent = in.readFloat();
      }

      this.final_aggregated_opportunity_value = in.readFloat();

      this.metric_used_for_yield_calculation = in.readString(this.metric_used_for_yield_calculation instanceof Utf8 ? (Utf8)this.metric_used_for_yield_calculation : null);

      this.metric_used_for_worth_calculation = in.readString(this.metric_used_for_worth_calculation instanceof Utf8 ? (Utf8)this.metric_used_for_worth_calculation : null);

      this.funnel_used_for_yield_calculation = in.readString(this.funnel_used_for_yield_calculation instanceof Utf8 ? (Utf8)this.funnel_used_for_yield_calculation : null);

      this.funnel_used_for_worth_calculation = in.readString(this.funnel_used_for_worth_calculation instanceof Utf8 ? (Utf8)this.funnel_used_for_worth_calculation : null);

      this.data_calculated_at = in.readLong();

      this.data_considered_upto = in.readLong();

    } else {
      for (int i = 0; i < 25; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.campaign_id = in.readLong();
          break;

        case 1:
          this.campaign_priority = in.readInt();
          break;

        case 2:
          this.deal_product_id = in.readString(this.deal_product_id instanceof Utf8 ? (Utf8)this.deal_product_id : null);
          break;

        case 3:
          this.ad_set_id = in.readLong();
          break;

        case 4:
          this.advertiser_type = com.paytmlabs.adtech.adtechdecisionengine.schema.audit.AdvertiserType.values()[in.readEnum()];
          break;

        case 5:
          this.yield_value = in.readFloat();
          break;

        case 6:
          this.objective_worth = in.readFloat();
          break;

        case 7:
          this.probability_of_objective = in.readFloat();
          break;

        case 8:
          this.worth_value = in.readFloat();
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.worth_funnel_occurrence = null;
          } else {
            this.worth_funnel_occurrence = in.readLong();
          }
          break;

        case 10:
          this.yield_worth_factor = in.readFloat();
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.yield_funnel_occurrence = null;
          } else {
            this.yield_funnel_occurrence = in.readLong();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.yield_prediction_metric = null;
          } else {
            this.yield_prediction_metric = in.readFloat();
          }
          break;

        case 13:
          this.aggregated_opportunity_value = in.readFloat();
          break;

        case 14:
          this.acceleration_factor = in.readFloat();
          break;

        case 15:
          this.pacing_factor = in.readFloat();
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.budget_spent = null;
          } else {
            this.budget_spent = in.readFloat();
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.percentage_budget_spent = null;
          } else {
            this.percentage_budget_spent = in.readFloat();
          }
          break;

        case 18:
          this.final_aggregated_opportunity_value = in.readFloat();
          break;

        case 19:
          this.metric_used_for_yield_calculation = in.readString(this.metric_used_for_yield_calculation instanceof Utf8 ? (Utf8)this.metric_used_for_yield_calculation : null);
          break;

        case 20:
          this.metric_used_for_worth_calculation = in.readString(this.metric_used_for_worth_calculation instanceof Utf8 ? (Utf8)this.metric_used_for_worth_calculation : null);
          break;

        case 21:
          this.funnel_used_for_yield_calculation = in.readString(this.funnel_used_for_yield_calculation instanceof Utf8 ? (Utf8)this.funnel_used_for_yield_calculation : null);
          break;

        case 22:
          this.funnel_used_for_worth_calculation = in.readString(this.funnel_used_for_worth_calculation instanceof Utf8 ? (Utf8)this.funnel_used_for_worth_calculation : null);
          break;

        case 23:
          this.data_calculated_at = in.readLong();
          break;

        case 24:
          this.data_considered_upto = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










