/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;
@org.apache.avro.specific.AvroGenerated
public enum AssetSelectionStrategy implements org.apache.avro.generic.GenericEnumSymbol<AssetSelectionStrategy> {
  SINGLE, RANDOM, PERFORMANCE_BASED, EXTERNAL, AOV  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AssetSelectionStrategy\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"symbols\":[\"SINGLE\",\"RANDOM\",\"PERFORMANCE_BASED\",\"EXTERNAL\",\"AOV\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
