/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;
@org.apache.avro.specific.AvroGenerated
public enum CampaignPriorityConfig implements org.apache.avro.generic.GenericEnumSymbol<CampaignPriorityConfig> {
  EXTERNAL_HIGHEST_WINS, MIXED_HIGHEST_WINS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CampaignPriorityConfig\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"symbols\":[\"EXTERNAL_HIGHEST_WINS\",\"MIXED_HIGHEST_WINS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
