/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RankingDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7144395984534820815L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RankingDetails\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"fields\":[{\"name\":\"algo\",\"type\":{\"type\":\"enum\",\"name\":\"RankingAlgorithm\",\"symbols\":[\"RANDOM\",\"TEMP_TARGETED\",\"CAMPAIGN_ID\",\"CAMPAIGN_SCORES\",\"EXTERNAL\",\"COST_PER_DELIVERY\",\"AOV_VALUE\",\"NONE\"]}},{\"name\":\"score\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"source_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"campaign_category\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RankingDetails> ENCODER =
      new BinaryMessageEncoder<RankingDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RankingDetails> DECODER =
      new BinaryMessageDecoder<RankingDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RankingDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RankingDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RankingDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RankingDetails>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RankingDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RankingDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RankingDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RankingDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm algo;
  private java.lang.Float score;
  private java.lang.CharSequence source_id;
  private java.lang.CharSequence campaign_category;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RankingDetails() {}

  /**
   * All-args constructor.
   * @param algo The new value for algo
   * @param score The new value for score
   * @param source_id The new value for source_id
   * @param campaign_category The new value for campaign_category
   */
  public RankingDetails(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm algo, java.lang.Float score, java.lang.CharSequence source_id, java.lang.CharSequence campaign_category) {
    this.algo = algo;
    this.score = score;
    this.source_id = source_id;
    this.campaign_category = campaign_category;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return algo;
    case 1: return score;
    case 2: return source_id;
    case 3: return campaign_category;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: algo = (com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm)value$; break;
    case 1: score = (java.lang.Float)value$; break;
    case 2: source_id = (java.lang.CharSequence)value$; break;
    case 3: campaign_category = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'algo' field.
   * @return The value of the 'algo' field.
   */
  public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm getAlgo() {
    return algo;
  }


  /**
   * Sets the value of the 'algo' field.
   * @param value the value to set.
   */
  public void setAlgo(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm value) {
    this.algo = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public java.lang.Float getScore() {
    return score;
  }


  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Float value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'source_id' field.
   * @return The value of the 'source_id' field.
   */
  public java.lang.CharSequence getSourceId() {
    return source_id;
  }


  /**
   * Sets the value of the 'source_id' field.
   * @param value the value to set.
   */
  public void setSourceId(java.lang.CharSequence value) {
    this.source_id = value;
  }

  /**
   * Gets the value of the 'campaign_category' field.
   * @return The value of the 'campaign_category' field.
   */
  public java.lang.CharSequence getCampaignCategory() {
    return campaign_category;
  }


  /**
   * Sets the value of the 'campaign_category' field.
   * @param value the value to set.
   */
  public void setCampaignCategory(java.lang.CharSequence value) {
    this.campaign_category = value;
  }

  /**
   * Creates a new RankingDetails RecordBuilder.
   * @return A new RankingDetails RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder newBuilder() {
    return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder();
  }

  /**
   * Creates a new RankingDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RankingDetails RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder newBuilder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder other) {
    if (other == null) {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder();
    } else {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder(other);
    }
  }

  /**
   * Creates a new RankingDetails RecordBuilder by copying an existing RankingDetails instance.
   * @param other The existing instance to copy.
   * @return A new RankingDetails RecordBuilder
   */
  public static com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder newBuilder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails other) {
    if (other == null) {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder();
    } else {
      return new com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for RankingDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RankingDetails>
    implements org.apache.avro.data.RecordBuilder<RankingDetails> {

    private com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm algo;
    private java.lang.Float score;
    private java.lang.CharSequence source_id;
    private java.lang.CharSequence campaign_category;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.algo)) {
        this.algo = data().deepCopy(fields()[0].schema(), other.algo);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.score)) {
        this.score = data().deepCopy(fields()[1].schema(), other.score);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.source_id)) {
        this.source_id = data().deepCopy(fields()[2].schema(), other.source_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.campaign_category)) {
        this.campaign_category = data().deepCopy(fields()[3].schema(), other.campaign_category);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing RankingDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.algo)) {
        this.algo = data().deepCopy(fields()[0].schema(), other.algo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.score)) {
        this.score = data().deepCopy(fields()[1].schema(), other.score);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source_id)) {
        this.source_id = data().deepCopy(fields()[2].schema(), other.source_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.campaign_category)) {
        this.campaign_category = data().deepCopy(fields()[3].schema(), other.campaign_category);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'algo' field.
      * @return The value.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm getAlgo() {
      return algo;
    }


    /**
      * Sets the value of the 'algo' field.
      * @param value The value of 'algo'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder setAlgo(com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm value) {
      validate(fields()[0], value);
      this.algo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'algo' field has been set.
      * @return True if the 'algo' field has been set, false otherwise.
      */
    public boolean hasAlgo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'algo' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder clearAlgo() {
      algo = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'score' field.
      * @return The value.
      */
    public java.lang.Float getScore() {
      return score;
    }


    /**
      * Sets the value of the 'score' field.
      * @param value The value of 'score'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder setScore(java.lang.Float value) {
      validate(fields()[1], value);
      this.score = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'score' field has been set.
      * @return True if the 'score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'score' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder clearScore() {
      score = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getSourceId() {
      return source_id;
    }


    /**
      * Sets the value of the 'source_id' field.
      * @param value The value of 'source_id'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder setSourceId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.source_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'source_id' field has been set.
      * @return True if the 'source_id' field has been set, false otherwise.
      */
    public boolean hasSourceId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'source_id' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder clearSourceId() {
      source_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaign_category' field.
      * @return The value.
      */
    public java.lang.CharSequence getCampaignCategory() {
      return campaign_category;
    }


    /**
      * Sets the value of the 'campaign_category' field.
      * @param value The value of 'campaign_category'.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder setCampaignCategory(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.campaign_category = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_category' field has been set.
      * @return True if the 'campaign_category' field has been set, false otherwise.
      */
    public boolean hasCampaignCategory() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'campaign_category' field.
      * @return This builder.
      */
    public com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingDetails.Builder clearCampaignCategory() {
      campaign_category = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RankingDetails build() {
      try {
        RankingDetails record = new RankingDetails();
        record.algo = fieldSetFlags()[0] ? this.algo : (com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm) defaultValue(fields()[0]);
        record.score = fieldSetFlags()[1] ? this.score : (java.lang.Float) defaultValue(fields()[1]);
        record.source_id = fieldSetFlags()[2] ? this.source_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.campaign_category = fieldSetFlags()[3] ? this.campaign_category : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RankingDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<RankingDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RankingDetails>
    READER$ = (org.apache.avro.io.DatumReader<RankingDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.algo.ordinal());

    if (this.score == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.score);
    }

    if (this.source_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.source_id);
    }

    if (this.campaign_category == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.campaign_category);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.algo = com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.score = null;
      } else {
        this.score = in.readFloat();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.source_id = null;
      } else {
        this.source_id = in.readString(this.source_id instanceof Utf8 ? (Utf8)this.source_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.campaign_category = null;
      } else {
        this.campaign_category = in.readString(this.campaign_category instanceof Utf8 ? (Utf8)this.campaign_category : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.algo = com.paytmlabs.adtech.adtechdecisionengine.schema.audit.RankingAlgorithm.values()[in.readEnum()];
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.score = null;
          } else {
            this.score = in.readFloat();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.source_id = null;
          } else {
            this.source_id = in.readString(this.source_id instanceof Utf8 ? (Utf8)this.source_id : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.campaign_category = null;
          } else {
            this.campaign_category = in.readString(this.campaign_category instanceof Utf8 ? (Utf8)this.campaign_category : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










