/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;
@org.apache.avro.specific.AvroGenerated
public enum RankingAlgorithm implements org.apache.avro.generic.GenericEnumSymbol<RankingAlgorithm> {
  RANDOM, TEMP_TARGETED, CAMPAIGN_ID, CAMPAIGN_SCORES, EXTERNAL, COST_PER_DELIVERY, AOV_VALUE, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RankingAlgorithm\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"symbols\":[\"RANDOM\",\"TEMP_TARGETED\",\"CAMPAIGN_ID\",\"CAMPAIGN_SCORES\",\"EXTERNAL\",\"COST_PER_DELIVERY\",\"AOV_VALUE\",\"NONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
