/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.paytmlabs.adtech.adtechdecisionengine.schema.audit;
@org.apache.avro.specific.AvroGenerated
public enum SelectionAlgorithm implements org.apache.avro.generic.GenericEnumSymbol<SelectionAlgorithm> {
  INTERNAL, INTERNAL_AOV  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SelectionAlgorithm\",\"namespace\":\"com.paytmlabs.adtech.adtechdecisionengine.schema.audit\",\"symbols\":[\"INTERNAL\",\"INTERNAL_AOV\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
